trigger:
  - development
pool:
  name: Default
resources:
  repositories:
    - repository: appiumTests
      type: git
      name: Quotes Daily/Quotes_Daily_Appium
steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: gradlew
      gradleOptions: -Xmx3072m
      tasks: bundleRelease
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: app/build/outputs/bundle/release/app-release.aab
      ArtifactName: ReleaseAAB
      publishLocation: Container
  - checkout: appiumTests
  - script: |
      npm install
    workingDirectory: $(Build.SourcesDirectory)/appiumTests
    displayName: Install Node.js dependencies for Appium
  - script: |
      appium &  sleep 5
    displayName: Start Appium server
  - script: |
      npm test
    workingDirectory: $(Build.SourcesDirectory)/appiumTests
    displayName: Run Appium tests
  - task: GooglePlayRelease@4
    inputs:
      serviceConnection: Quotes Daily Service connection
      applicationId: com.app.quotes_daily
      bundleFile: app/build/outputs/bundle/release/app-release.aab
      track: alpha
      trackName: Closed testing - Closed Test Gamma