trigger:
  branches:
    include:
      - development   # Only trigger on development branch

pool:
  name: Default   # Self-hosted Mac agent

jobs:
  # Job 1: Build Release and Publish Artifact
  - job: ReleaseBuild
    displayName: "Build Release AAB"
    pool:
      name: Default
    steps:
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'bundleRelease'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'app/build/outputs/bundle/release/app-release.aab'
          ArtifactName: 'releaseBundle'
          publishLocation: 'Container'

  # Job 2: Run Appium Tests on Release AAB
  - job: RunAppiumTests
    displayName: "Run Appium Tests"
    dependsOn: ReleaseBuild
    pool:
      name: Default
    steps:
      # Ensure Java 11 Installed
      - script: |
          if ! java -version 2>&1 | grep '11.'; then
            echo "Java 11 not found. Installing..."
            brew tap homebrew/cask-versions
            brew install --cask temurin11
          else
            echo "Java 11 already installed."
          fi
          java -version
        displayName: "Ensure Java 11 Installed"

      # Checkout the Appium tests repo
      - checkout: self
      - checkout: Qoutes_Daily_Appium   # Appium repo (add in resources)

      # Download the Release AAB from artifacts
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'releaseBundle'
          downloadPath: '$(System.DefaultWorkingDirectory)'

      # Run Appium tests (Gradle)
      - script: |
          cd Qoutes_Daily_Appium
          ./gradlew clean test
        displayName: "Run Appium Tests"

      # ✅ Publish JUnit results into Azure DevOps Tests tab
      - task: PublishTestResults@2
        displayName: "Publish Appium Test Results"
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'Qoutes_Daily_Appium/build/test-results/test/TEST-*.xml'
          failTaskOnFailedTests: true

      # ✅ Publish HTML report as artifact
      - publish: Qoutes_Daily_Appium/build/reports/tests/test
        artifact: AppiumHtmlReport
        displayName: "Publish Appium HTML Report"

  # Job 3: Publish to Google Play (only if tests succeed)
  - job: PublishToPlayStore
    displayName: "Upload AAB to Google Play"
    dependsOn: RunAppiumTests
    condition: succeeded()
    pool:
      name: Default
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'releaseBundle'
          downloadPath: '$(System.DefaultWorkingDirectory)'

      - task: GooglePlayRelease@4
        inputs:
          serviceConnection: 'Quotes Daily Service connection'
          applicationId: 'com.app.quotes_daily'
          bundleFile: '$(System.DefaultWorkingDirectory)/releaseBundle/app-release.aab'
          track: 'alpha'
          trackName: 'Closed testing - Closed Test Gamma'
