trigger:
  - development

pool:
  name: Default   # Your self-hosted Mac agent

resources:
  repositories:
    - repository: appiumTests
      type: git
      name: Quotes Daily/Quotes_Daily_Appium   # Project/Repo format

steps:
  # Disable default checkout of self first
  - checkout: none

  # Checkout main repo (Android app)
  - checkout: self

  # Checkout Appium repo
  - checkout: appiumTests

  # 1️⃣ Build Release AAB
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'bundleRelease'   # generates .aab

  # 2️⃣ Publish AAB as artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'app/build/outputs/bundle/release/app-release.aab'
      ArtifactName: 'ReleaseAAB'
      publishLocation: 'Container'

  # 3️⃣ Install Node.js dependencies for Appium tests
  - script: |
      npm install
    workingDirectory: '$(Build.SourcesDirectory)/appiumTests'
    displayName: 'Install Node.js dependencies for Appium'

  # 4️⃣ Start Appium server
  - script: |
      appium &   # Start Appium in background
      sleep 5
    displayName: 'Start Appium server'

  # 5️⃣ Run Appium tests
  - script: |
      npm test
    workingDirectory: '$(Build.SourcesDirectory)/appiumTests'
    displayName: 'Run Appium tests'

  # 6️⃣ Upload AAB to Google Play only if tests pass
  - task: GooglePlayRelease@4
    inputs:
      serviceConnection: 'Quotes Daily Service connection'
      applicationId: 'com.app.quotes_daily'
      bundleFile: 'app/build/outputs/bundle/release/app-release.aab'
      track: 'alpha'
      trackName: 'Closed testing - Closed Test Gamma'
