trigger:
  - development

pool:
  name: Default

resources:
  repositories:
    - repository: another_repo
      type: git
      name: "Quotes Daily/Qoutes_Daily_Appium"

steps:
  - checkout: self
  - checkout: another_repo
