trigger:
  branches:
    include:
      - development   # Trigger only on development branch

pool:
  name: "Azure Pipelines"   # Self-hosted Mac agent

resources:
  repositories:
    - repository: appiumTests
      type: git
      name: "Quotes Daily/Qoutes_Daily_Appium"

jobs:
  # Job 1: Build Release APK and publish artifact
  - job: BuildReleaseAPK
    displayName: "Build Release APK"
    pool:
      name: Default
    steps:
      # Clean checkout of main repo
      - checkout: self
        clean: true

      # Gradle build for APK
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'assembleRelease'

      # Publish APK artifact
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'app/build/outputs/apk/release/app-release.apk'
          ArtifactName: 'releaseApk'
          publishLocation: 'Container'

