trigger:
  - development   # manual run only, so we can test safely

pool:
  name: Default   # Your self-hosted Mac agent



steps:
  # Checkout main repo (self)
  - checkout: self
    displayName: "Checkout Android repo"


  # Show folder structure to verify both repos are present
  - script: |
      echo "=== Repo Folders ==="
      ls -R $(Build.SourcesDirectory)
    displayName: "List files after checkout"
