trigger:
  branches:
    include:
      - development   # Trigger only on development branch

pool:
  name: Default   # Self-hosted Mac agent

resources:
  repositories:
    - repository: appiumTests
      type: git
      name: "Quotes Daily/Qoutes_Daily_Appium"

jobs:
  # Job 1: Build Release APK and publish artifact
  - job: BuildReleaseAPK
    displayName: "Build Release APK"
    pool:
      name: Default
    steps:
      # Clean checkout of main repo
      - checkout: self
        clean: true

      # Gradle build for APK
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'assembleRelease'

      # Publish APK artifact
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'app/build/outputs/apk/release/app-release.apk'
          ArtifactName: 'releaseApk'
          publishLocation: 'Container'

  # Job 2: Run Appium Tests
  - job: RunAppiumTests
    displayName: "Run Appium Tests"
    dependsOn: BuildReleaseAPK
    pool:
      name: Default
    steps:
      # Checkout main repo
      - checkout: self
        clean: true
        path: 'main'

      # Checkout Appium tests repository
      - checkout: appiumTests
        clean: true
        path: 'appium'

      # Download the built APK artifact
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'releaseApk'
          downloadPath: '$(System.ArtifactsDirectory)'

      # Setup Java 8 for Android SDK compatibility
      - script: |
          echo "Installing Java 8 for Android SDK compatibility..."
          
          # Check if Homebrew is installed
          if ! command -v brew &> /dev/null; then
            echo "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            # Add Homebrew to PATH for current session
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          fi
          
          # Always install Java 8 to ensure compatibility
          echo "Installing/updating OpenJDK 8..."
          brew install openjdk@8 || brew upgrade openjdk@8 || echo "Java 8 already installed"
          
          # Force set JAVA_HOME to Java 8
          export JAVA_HOME=$(brew --prefix openjdk@8)/libexec/openjdk.jdk/Contents/Home
          export PATH="$JAVA_HOME/bin:$PATH"
          
          echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
          echo "##vso[task.setvariable variable=PATH]$JAVA_HOME/bin:$PATH"
          
          echo "Java 8 setup completed"
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
        displayName: 'Force Java 8 Setup'

      # Setup Android SDK (if not already installed on the agent)
      - script: |
          # Check if Android SDK is already available
          if [ -z "$ANDROID_HOME" ]; then
            echo "ANDROID_HOME not set, setting up Android SDK..."
            # Set Android SDK path (adjust based on your agent setup)
            export ANDROID_HOME=/usr/local/share/android-sdk
            export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
            echo "##vso[task.setvariable variable=ANDROID_HOME]$ANDROID_HOME"
            echo "##vso[task.setvariable variable=PATH]$PATH"
          else
            echo "Android SDK found at: $ANDROID_HOME"
          fi
          
          # Verify Android SDK tools
          which adb || echo "ADB not found in PATH"
          which emulator || echo "Emulator not found in PATH"
        displayName: 'Setup Android SDK'

      # Create and start Android emulator
      - script: |
          echo "Setting up Android emulator..."
          
          # Force Java 8 environment for Android SDK tools
          export JAVA_HOME=$(brew --prefix openjdk@8)/libexec/openjdk.jdk/Contents/Home
          export PATH="$JAVA_HOME/bin:$PATH"
          
          echo "Using Java 8 for Android SDK:"
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
          
          # Verify Java 8 is being used
          if ! java -version 2>&1 | grep -q "1.8\|openjdk 8"; then
            echo "ERROR: Java 8 not being used! Current version:"
            java -version
            echo "Attempting to force Java 8..."
            export PATH="$(brew --prefix openjdk@8)/bin:$PATH"
            java -version
          fi
          
          # Accept licenses
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
          
          # Detect architecture and install appropriate system images
          ARCH=$(uname -m)
          if [ "$ARCH" = "arm64" ]; then
            echo "Detected Apple Silicon (ARM64), using ARM64 system images"
            SYSTEM_IMAGE="system-images;android-30;google_apis;arm64-v8a"
          else
            echo "Detected Intel (x86_64), using x86_64 system images"
            SYSTEM_IMAGE="system-images;android-30;google_apis;x86_64"
          fi
          
          echo "Installing system image: $SYSTEM_IMAGE"
          
          # Install required SDK components
          if ! $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-30" "$SYSTEM_IMAGE"; then
            echo "SDK Manager failed. Trying with command line tools..."
            # Download command line tools if sdkmanager fails
            cd $ANDROID_HOME
            curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip
            unzip -q cmdline-tools.zip
            mkdir -p cmdline-tools/latest
            mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
            export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "platforms;android-30" "$SYSTEM_IMAGE"
          fi
          
          # Create AVD (Android Virtual Device)
          echo "Creating AVD with $SYSTEM_IMAGE..."
          
          # Method 1: Try with original avdmanager
          if echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n "test_emulator" -k "$SYSTEM_IMAGE" --force; then
            echo "AVD created successfully with tools/bin/avdmanager"
          # Method 2: Try with command line tools
          elif echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n "test_emulator" -k "$SYSTEM_IMAGE" --force; then
            echo "AVD created successfully with cmdline-tools"
          else
            # Method 3: Manual AVD creation
            echo "Both avdmanager methods failed. Creating AVD manually..."
            
            AVD_DIR="$HOME/.android/avd/test_emulator.avd"
            AVD_INI="$HOME/.android/avd/test_emulator.ini"
            
            mkdir -p "$AVD_DIR"
            mkdir -p "$HOME/.android/avd"
            
            # Create AVD config file
            cat > "$AVD_INI" << EOF
avd.ini.encoding=UTF-8
path=$AVD_DIR
path.rel=avd/test_emulator.avd
target=android-30
EOF

            # Create AVD directory config
            cat > "$AVD_DIR/config.ini" << EOF
AvdId=test_emulator
PlayStore.enabled=false
abi.type=arm64-v8a
avd.ini.displayname=test_emulator
avd.ini.encoding=UTF-8
disk.dataPartition.size=800MB
hw.accelerometer=yes
hw.arc=false
hw.audioInput=yes
hw.battery=yes
hw.camera.back=webcam0
hw.camera.front=webcam0
hw.cpu.arch=arm64
hw.cpu.ncore=4
hw.dPad=no
hw.device.hash2=MD5:6930e145748b87e87b14ffb4e762aeb3
hw.device.manufacturer=Google
hw.device.name=pixel
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=auto
hw.initialOrientation=Portrait
hw.keyboard=yes
hw.lcd.density=420
hw.lcd.height=1920
hw.lcd.width=1080
hw.mainKeys=no
hw.ramSize=1536
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-30/google_apis/arm64-v8a/
tag.display=Google APIs
tag.id=google_apis
vm.heapSize=256
EOF
            
            echo "Manual AVD creation completed"
          fi
          
          # Verify AVD was created
          echo "Checking available AVDs:"
          $ANDROID_HOME/emulator/emulator -list-avds
          
          # Verify the specific AVD exists
          if [ -f "$HOME/.android/avd/test_emulator.ini" ]; then
            echo "✓ test_emulator AVD found"
          else
            echo "✗ test_emulator AVD not found!"
            echo "Available AVD files:"
            ls -la "$HOME/.android/avd/" || echo "No AVD directory found"
          fi
          
          # Start emulator in background
          echo "Starting emulator..."
          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-window -no-audio -no-snapshot &
          
          # Wait for emulator to boot
          echo "Waiting for emulator to boot..."
          $ANDROID_HOME/platform-tools/adb wait-for-device
          
          # Wait for boot to complete
          BOOT_TIMEOUT=300  # 5 minutes
          ELAPSED=0
          while [ "`$ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r' `" != "1" ] && [ $ELAPSED -lt $BOOT_TIMEOUT ]; do
            echo "Still waiting for boot... ($ELAPSED/$BOOT_TIMEOUT seconds)"
            sleep 10
            ELAPSED=$((ELAPSED + 10))
          done
          
          if [ $ELAPSED -ge $BOOT_TIMEOUT ]; then
            echo "Emulator boot timeout reached!"
            exit 1
          fi
          
          echo "Emulator is ready!"
          $ANDROID_HOME/platform-tools/adb devices
        displayName: 'Create and Start Android Emulator'

      # List directories to debug the checkout
      - script: |
          echo "Build.SourcesDirectory contents:"
          ls -la $(Build.SourcesDirectory)
          echo "Looking for Java/Maven project files..."
          find $(Build.SourcesDirectory) -name "pom.xml" -type f
          find $(Build.SourcesDirectory) -name "build.gradle*" -type f
          echo "All directories in Build.SourcesDirectory:"
          find $(Build.SourcesDirectory) -type d -maxdepth 2
        displayName: 'Debug: List directories and find project files'

      # Find and prepare Appium test directory
      - script: |
          echo "Looking for Appium test directory..."
          # Check common directory names for the Appium repository
          APPIUM_DIR=""
          if [ -d "$(Build.SourcesDirectory)/appium" ]; then
            APPIUM_DIR="$(Build.SourcesDirectory)/appium"
          elif [ -d "$(Build.SourcesDirectory)/Qoutes_Daily_Appium" ]; then
            APPIUM_DIR="$(Build.SourcesDirectory)/Qoutes_Daily_Appium"
          else
            # Find any directory that contains pom.xml or build.gradle
            APPIUM_DIR=$(find $(Build.SourcesDirectory) -name "pom.xml" -o -name "build.gradle*" | head -1 | xargs dirname)
          fi
          
          if [ -n "$APPIUM_DIR" ] && [ -d "$APPIUM_DIR" ]; then
            echo "Found Appium directory: $APPIUM_DIR"
            echo "##vso[task.setvariable variable=APPIUM_TEST_DIR]$APPIUM_DIR"
            echo "Directory contents:"
            ls -la "$APPIUM_DIR"
          else
            echo "Could not find Appium test directory"
            exit 1
          fi
        displayName: 'Find Appium Test Directory'

      # Install APK on emulator
      - script: |
          APK_PATH="$(System.ArtifactsDirectory)/releaseApk/app-release.apk"
          echo "Installing APK on emulator: $APK_PATH"
          
          # Verify emulator is ready
          $ANDROID_HOME/platform-tools/adb devices
          
          # Install the APK
          $ANDROID_HOME/platform-tools/adb install -r "$APK_PATH"
          
          echo "APK installed successfully"
        displayName: 'Install APK on Emulator'

      # Run Appium tests
      - script: |
          # Set APK path and device info for tests
          export APK_PATH="$(System.ArtifactsDirectory)/releaseApk/app-release.apk"
          export DEVICE_NAME="test_emulator"
          export PLATFORM_VERSION="11.0"
          export AUTOMATION_NAME="UiAutomator2"
          
          echo "APK Path: $APK_PATH"
          echo "Device Name: $DEVICE_NAME"
          echo "Working in directory: $(APPIUM_TEST_DIR)"
          cd "$(APPIUM_TEST_DIR)"
          
          # Check for Maven or Gradle project
          if [ -f "pom.xml" ]; then
            echo "Found Maven project (pom.xml)"
            echo "Running Maven tests..."
            mvn clean test \
              -Dapp.path="$APK_PATH" \
              -Ddevice.name="$DEVICE_NAME" \
              -Dplatform.version="$PLATFORM_VERSION" \
              -Dautomation.name="$AUTOMATION_NAME"
          elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "Found Gradle project"
            echo "Running Gradle tests..."
            ./gradlew clean test \
              -Dapp.path="$APK_PATH" \
              -Ddevice.name="$DEVICE_NAME" \
              -Dplatform.version="$PLATFORM_VERSION" \
              -Dautomation.name="$AUTOMATION_NAME"
          else
            echo "No recognized Java build file found (pom.xml or build.gradle)"
            echo "Directory contents:"
            ls -la
            exit 1
          fi
        displayName: 'Run Appium Tests'

      # Cleanup emulator
      - script: |
          echo "Stopping emulator..."
          $ANDROID_HOME/platform-tools/adb emu kill
        displayName: 'Stop Emulator'
        condition: always()

      # Publish test results (optional - adjust based on your test output format)
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: |
            **/target/surefire-reports/TEST-*.xml
            **/build/test-results/test/TEST-*.xml
          searchFolder: '$(APPIUM_TEST_DIR)'
        displayName: 'Publish Test Results'