trigger:
  - development  # run pipeline on development branch
  -

pool:
  agent: Default

variables:
  ANDROID_SDK_ROOT: $(HOME)/Library/Android/sdk
  EMULATOR_NAME: "Pixel_3_API_33"
  API_LEVEL: "33"
  DEVICE: "pixel_3"

jobs:
  - job: RunAndroidEmulator
    displayName: "Create and Run Android Emulator"
    steps:
      # 1. Install SDK tools
      - task: Bash@3
        displayName: "Install Android SDK Tools"
        inputs:
          targetType: 'inline'
          script: |
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "platforms;android-$(API_LEVEL)" "emulator" "system-images;android-$(API_LEVEL);google_apis;x86_64"

      # 2. Create emulator
      - task: Bash@3
        displayName: "Create Android Emulator"
        inputs:
          targetType: 'inline'
          script: |
            echo "no" | avdmanager create avd -n $(EMULATOR_NAME) -k "system-images;android-$(API_LEVEL);google_apis;x86_64" --device "$(DEVICE)"

      # 3. Start emulator in background
      - task: Bash@3
        displayName: "Start Android Emulator"
        inputs:
          targetType: 'inline'
          script: |
            nohup emulator -avd $(EMULATOR_NAME) -no-snapshot -no-window -gpu swiftshader_indirect &

      # 4. Wait for emulator to boot
      - task: Bash@3
        displayName: "Wait for Emulator to Boot"
        inputs:
          targetType: 'inline'
          script: |
            echo "Waiting for emulator to start..."
            adb wait-for-device
            boot_completed=""
            until [[ "$boot_completed" =~ "1" ]]; do
              boot_completed=$(adb shell getprop sys.boot_completed 2>&1)
              sleep 5
            done
            echo "Emulator is ready!"
