pool:
  name: Default   # Your self-hosted Mac agent

steps:
  # 1️⃣ Build Release Bundle
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'bundleRelease'

  # 2️⃣ Upload to Google Play
  - task: GooglePlayRelease@4
    inputs:
      serviceConnection: 'Quotes Daily Service connection'
      applicationId: 'com.app.quotes_daily'
      bundleFile: 'app/build/outputs/bundle/release/app-release.aab'
      track: 'alpha'
      trackName: 'Closed testing - Closed Test Gamma'
