trigger:
  branches:
    include:
      - development   # Only trigger on development branch

pool:
  name: Default   # Self-hosted Mac agent

jobs:
  # Job 1: Build Release and Publish Artifact
  - job: ReleaseBuild
    displayName: "Build Release AAB"
    pool:
      name: Default
    steps:
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'bundleRelease'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'app/build/outputs/bundle/release/app-release.aab'
          ArtifactName: 'releaseBundle'
          publishLocation: 'Container'

  # Job 2: Run Appium Tests on Release AAB
  - job: RunAppiumTests
    displayName: "Run Appium Tests"
    dependsOn: ReleaseBuild
    pool:
      name: Default
    steps:
      # Check if Java 11 is installed, if not install
      - script: |
          if ! java -version 2>&1 | grep '11.'; then
            echo "Java 11 not found. Installing..."
            brew tap homebrew/cask-versions
            brew install --cask temurin11
          else
            echo "Java 11 already installed."
          fi
          java -version
        displayName: "Ensure Java 11 Installed"

      # Download the Release AAB from artifacts
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'releaseBundle'
          downloadPath: '$(System.DefaultWorkingDirectory)'

      # Run Appium tests (make sure repo is added as resource)
      - script: |
          cd ../Qoutes_Daily_Appium
          ./gradlew clean test -PappPath=$(System.DefaultWorkingDirectory)/releaseBundle/app-release.aab
        displayName: "Run Appium Tests"

  # Job 3: Publish to Google Play (only if tests succeed)
  - job: PublishToPlayStore
    displayName: "Upload AAB to Google Play"
    dependsOn:
      - RunAppiumTests   # depends on Appium test job
    condition: succeeded('RunAppiumTests')   # publish only if tests succeed
    pool:
      name: Default
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'releaseBundle'
          downloadPath: '$(System.DefaultWorkingDirectory)'

      - task: GooglePlayRelease@4
        inputs:
          serviceConnection: 'Quotes Daily Service connection'
          applicationId: 'com.app.quotes_daily'
          bundleFile: '$(System.DefaultWorkingDirectory)/releaseBundle/app-release.aab'
          track: 'alpha'
          trackName: 'Closed testing - Closed Test Gamma'
