trigger: none

pool:
  name: Development

resources:
  repositories:
    - repository: appiumTests
      type: git
      name: "Quotes Daily/Quotes_Daily_Appium"

steps:
  - checkout: self
  - checkout: appiumTests
  - script: |
      echo "=== Android Repo (self) ==="
      ls -R $(Build.SourcesDirectory)

      echo "=== Appium Repo ==="
      ls -R $(Build.SourcesDirectory)/appiumTests
