trigger:
  - development

pool:
  name: Default   # Your self-hosted Mac agent

resources:
  repositories:
    - repository: appiumTests
      type: git
      name: 'Quotes Daily/Quotes_Daily_Appium'   # Project/Repo format

variables:
  aabPath: 'app/build/outputs/bundle/release/app-release.aab'

steps:
  # Disable default checkout of self first
  - checkout: none

  # Checkout main repo (Android app)
  - checkout: self

  # Checkout Appium repo
  - checkout: appiumTests

  # 1️⃣ Build Release AAB
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'bundleRelease'   # generates .aab
    displayName: 'Build Release AAB'

  # 2️⃣ Publish AAB as artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(aabPath)'
      ArtifactName: 'ReleaseAAB'
      publishLocation: 'Container'
    displayName: 'Publish AAB as Artifact'

  # 3️⃣ Install Node.js dependencies for Appium tests
  - script: |
      npm install
    workingDirectory: '$(Build.SourcesDirectory)/appiumTests'
    displayName: 'Install Node.js dependencies for Appium'

  # 4️⃣ Start Appium server
  - script: |
      appium &
      sleep 5
    displayName: 'Start Appium server'

  # 5️⃣ Run Appium tests
  - script: |
      npm test
    workingDirectory: '$(Build.SourcesDirectory)/appiumTests'
    displayName: 'Run Appium tests'

  # 6️⃣ Upload AAB to Google Play only if tests pass
  - task: GooglePlayRelease@4
    inputs:
      serviceConnection: 'Quotes Daily Service connection'
      applicationId: 'com.app.quotes_daily'
      bundleFile: '$(aabPath)'
      track: 'alpha'
      trackName: 'Closed testing - Closed Test Gamma'
    displayName: 'Upload to Google Play Store'