# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - feature/azure_closes_testing

pool:
  name: Default   # your self-hosted pool

steps:
  # Run Gradle to build Release AAB
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'bundleRelease'

  # Publish the generated AAB as an artifact so you can download it
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'app/build/outputs/bundle/release/app-release.aab'
      ArtifactName: 'release-aab'
      publishLocation: 'Container'
