trigger:
  branches:
    include:
      - development   # Only trigger on development branch

pool:
  name: Default   # Self-hosted Mac agent

jobs:
  # Job 1: Build Release APK and publish artifact
  - job: BuildReleaseAPK
    displayName: "Build Release APK"
    pool:
      name: Default
    steps:
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'assembleRelease'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'app/build/outputs/apk/release/app-release.apk'
          ArtifactName: 'releaseApk'
          publishLocation: 'Container'

  # Job 2: Run Appium Tests using APK
  - job: RunAppiumTests
    displayName: "Run Appium Tests"
    dependsOn: BuildReleaseAPK
    pool:
      name: Default
    steps:
      - script: |
          if ! java -version 2>&1 | grep '11.'; then
            echo "Java 11 not found. Installing..."
            brew tap homebrew/cask-versions
            brew install --cask temurin11
          fi
          java -version
        displayName: "Ensure Java 11 Installed"

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'releaseApk'
          downloadPath: '$(System.DefaultWorkingDirectory)'

      - script: |
          cd ../Qoutes_Daily_Appium
          ./gradlew clean test -PappPath=$(System.DefaultWorkingDirectory)/releaseApk/app-release.apk
        displayName: "Run Appium Tests"

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/build/test-results/test/TEST-*.xml'
          testRunTitle: 'Appium Test Results'

  # Job 3: Build Release AAB and publish artifact (only if tests succeed)
  - job: BuildReleaseAAB
    displayName: "Build Release AAB"
    dependsOn: RunAppiumTests
    condition: succeeded('RunAppiumTests')
    pool:
      name: Default
    steps:
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'bundleRelease'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'app/build/outputs/bundle/release/app-release.aab'
          ArtifactName: 'releaseBundle'
          publishLocation: 'Container'

  # Job 4: Publish AAB to Google Play (only if tests succeed)
  - job: PublishToPlayStore
    displayName: "Upload AAB to Google Play"
    dependsOn: BuildReleaseAAB
    condition: succeeded('BuildReleaseAAB')
    pool:
      name: Default
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'releaseBundle'
          downloadPath: '$(System.DefaultWorkingDirectory)'

      - task: GooglePlayRelease@4
        inputs:
          serviceConnection: 'Quotes Daily Service connection'
          applicationId: 'com.app.quotes_daily'
          bundleFile: '$(System.DefaultWorkingDirectory)/releaseBundle/app-release.aab'
          track: 'alpha'
          trackName: 'Closed testing - Closed Test Gamma'
