trigger:
  - feature/azure_closes_testing

pool:
  name: Default   # Your self-hosted pool on Mac

steps:
  # Step 1: Build the Release AAB
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'bundleRelease'

  # Step 2: Publish to Google Play Closed Testing (Gamma)
  - task: GooglePlayRelease@4
    inputs:
      serviceConnection: 'Quotes Daily Service connection'   # Name of your Google Play service connection in Azure
      applicationId: 'com.app.quotes_daily'               # Replace with your app’s packageName from Play Console
      bundleFile: 'app/build/outputs/bundle/release/app-release.aab'
      track: 'alpha'
      trackName: 'Closed Test Gamma'
